// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb98XDRUykpm5tz3psLLekOuYwXokCptU',
    appId: '1:623837380180:web:bd87041e5011f89694f7c1',
    messagingSenderId: '623837380180',
    projectId: 'cbnhre-8ddd5',
    authDomain: 'cbnhre-8ddd5.firebaseapp.com',
    storageBucket: 'cbnhre-8ddd5.firebasestorage.app',
    measurementId: 'G-PP7YLWLFXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzGIo4TvvXbvfcSe5rp4ePgOgIwwCREOI',
    appId: '1:623837380180:android:b56075ac0ff9097c94f7c1',
    messagingSenderId: '623837380180',
    projectId: 'cbnhre-8ddd5',
    storageBucket: 'cbnhre-8ddd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn9BqEH4aM5qK8jUr3nj9T7cg-GQoV4Ls',
    appId: '1:623837380180:ios:d6652fbd2301a96994f7c1',
    messagingSenderId: '623837380180',
    projectId: 'cbnhre-8ddd5',
    storageBucket: 'cbnhre-8ddd5.firebasestorage.app',
    iosClientId: '623837380180-op0gumo3f5ak9612g29ddrg00gh3ajeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn9BqEH4aM5qK8jUr3nj9T7cg-GQoV4Ls',
    appId: '1:623837380180:ios:d6652fbd2301a96994f7c1',
    messagingSenderId: '623837380180',
    projectId: 'cbnhre-8ddd5',
    storageBucket: 'cbnhre-8ddd5.firebasestorage.app',
    iosClientId: '623837380180-op0gumo3f5ak9612g29ddrg00gh3ajeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb98XDRUykpm5tz3psLLekOuYwXokCptU',
    appId: '1:623837380180:web:d38cdb0c7645b68a94f7c1',
    messagingSenderId: '623837380180',
    projectId: 'cbnhre-8ddd5',
    authDomain: 'cbnhre-8ddd5.firebaseapp.com',
    storageBucket: 'cbnhre-8ddd5.firebasestorage.app',
    measurementId: 'G-GDY55KJL0K',
  );
}
